version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: live026
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./scripts:/scripts
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
